version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uefs-netra-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - uefs-netra-network
    depends_on:
      - postgres
      - redis  # ← Adicione esta linha

  nginx:
    image: nginx:alpine
    container_name: uefs-netra-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - uefs-netra-network
    depends_on:
      - app

  postgres:
    image: postgres:14
    container_name: uefs-netra-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: uefs_netra
      POSTGRES_USER: uefs_user
      POSTGRES_PASSWORD: uefs_password
    ports:
      - "8001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - uefs-netra-network

  redis:  # ← Adicione este serviço
    image: redis:7-alpine
    container_name: uefs-netra-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - uefs-netra-network

volumes:
  postgres_data:
  redis_data:  # ← Adicione este volume

networks:
  uefs-netra-network:
    driver: bridge
